---
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: buildpack-nodejs-buildrun-namespaced-heroku
spec:
  build:
    name: buildpack-nodejs-build-namespaced-heroku
  serviceAccount: ".generate"
